[#--公共参数存放--]
[#if Session["user"]??]
    [#assign user=Session["user"] /]
[/#if]
[#--静态资源版本号--]
[#if Session["staticVersion"]??]
    [#assign staticVersion=Session["staticVersion"] /]
[/#if]
[#assign basePath=request.contextPath /]
[#assign baseResourcePath=basePath+springMacroRequestContext.getWebApplicationContext().getEnvironment().getProperty("local.static-path-pattern") /]
[#--自定义宏指令引入--]
[#include "baseMacro.ftl"]